### ISSUE TITLE
恒生聚源数据是付费的吗

### ISSUE THREAD

**Issue by weituotian** [PengchuanC/fund_vue3#1]
数据是付费的吗？

**Comment by weituotian** [comment]
问一下是自己抓包客户端数据，还是要付费购买

**Comment by PengchuanC** [comment]
> 问一下是自己抓包客户端数据，还是要付费购买

数据是付费的，需要采购

**Comment by weituotian** [comment]
好~(￣▽￣)~*

**Comment by weituotian** [comment]
> > 问一下是自己抓包客户端数据，还是要付费购买
> 
> 数据是付费的，需要采购

好的明白了，谢谢，这年头太难了

**Comment by weituotian** [comment]
@PengchuanC 还有个问题请教下，比如说基金代码165312，我抓包恒生聚源的时候，发现恒生聚源的复权净值没有考虑到拆分。而它的html页面好像只有分红数据，没有拆分数据。麻烦能帮忙确认一下吗？如果有条件可以对比下wind或其它金融客户端的复权净值数据，恒生聚源的复权净值不太对的哦

**Comment by PengchuanC** [comment]
复权净值没有拆分什么意思，复权净值是考虑红利再投资的，如果只想看红利，可以使用累计净值，另外聚源的复权净值与wind实际上确实会有区别，但如果计算涨跌幅的话，二者是一致的。实际上，基金公司只会披露单位净值和累积竞争，赋权净值为各数据供应商自己计算的，你也可以根据单位净值和累计净值计算出复权净值。

**Comment by weituotian** [comment]
> 复权净值没有拆分什么意思，复权净值是考虑红利再投资的，如果只想看红利，可以使用累计净值，另外聚源的复权净值与wind实际上确实会有区别，但如果计算涨跌幅的话，二者是一致的。实际上，基金公司只会披露单位净值和累积竞争，赋权净值为各数据供应商自己计算的，你也可以根据单位净值和累计净值计算出复权净值。

复权净值可以自己算，但分红和拆分都会影响单位净值，被计算进**复权因子**中（累乘，分红根据分红金额除权日计算进去，拆分就根据拆分比例计算进去）。单位净值乘以复权因子就是**复权净值**了。我是在聚宽这个平台了解到复权净值的。然后恒生聚源的复权净值没有考虑到基金拆分，即没有加算拆分比例进到复权因子中，所以复权净值是小一点的，不知道你在wind是否看到恒生聚源的复权净值比wind小，就以000674为例（既有拆分也有分红）

**Comment by weituotian** [comment]
000674为例

东方choice导出：
![image](https://user-images.githubusercontent.com/7270968/160240498-32628186-1eab-4878-b212-4050eac08534.png)

恒生聚源：
![image](https://user-images.githubusercontent.com/7270968/160240521-1b99f332-84b9-4bf9-b617-278e4b3685ca.png)

可以看到恒生聚源比东方财富的复权净值小

**Comment by PengchuanC** [comment]
> 000674为例
> 
> 东方choice导出： ![image](https://user-images.githubusercontent.com/7270968/160240498-32628186-1eab-4878-b212-4050eac08534.png)
> 
> 恒生聚源： ![image](https://user-images.githubusercontent.com/7270968/160240521-1b99f332-84b9-4bf9-b617-278e4b3685ca.png)
> 
> 可以看到恒生聚源比东方财富的复权净值小

000674这类基金比较特殊，是有由分级基金转换而来的，这类基金聚源会重转换后开始，重新计算复权净值，wind则还是延续原来的产品净值，继续计算，这也是聚源复权净值比wind小的原因。实际上，聚源数据库会有一张专门的表单，来记录转换基金的整转换前后拼接的复权净值。

**Comment by PengchuanC** [comment]
> 

我记得这类基金叫“转型基金”，常见的有分级基金转普通基金，场外转场内
